<?php
/*
 * Plugin Name:       Interactive Node Map
 * Description:       Interactive world map plugin for WordPress.
 * Version:           1.1.0
 * Requires at least: 5.2
 * Requires PHP:      5.2
 * Author:            IK Robin
 * License:           GPL-2.0+
 * Text Domain:       interactive-world-maps-wp
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/* ---------- Plugin constants ---------- */
if ( ! defined( 'IKRWMAP_ROBIN_DIR_PATH_WORLD' ) ) {
    define( 'IKRWMAP_ROBIN_DIR_PATH_WORLD', plugin_dir_path( __FILE__ ) );
}

/* ---------- Include original functions file (admin pages, enqueues, ajax handlers etc.) ---------- */
if ( file_exists( IKRWMAP_ROBIN_DIR_PATH_WORLD . 'functions/functions.php' ) ) {
    include_once IKRWMAP_ROBIN_DIR_PATH_WORLD . 'functions/functions.php';
}

/* ---------- Include DB setup ---------- */
if ( file_exists( IKRWMAP_ROBIN_DIR_PATH_WORLD . 'includes/db.php' ) ) {
    include_once IKRWMAP_ROBIN_DIR_PATH_WORLD . 'includes/db.php';
}

/* ---------- Admin menu (kept intact) ---------- */
function ikrwmap_add_menu_page() {
    add_menu_page( 'interactive-node-map', 'Node Map', 'manage_options', 'interactive-node-map', 'ikrwmap_ikrwmap_add_admin_menu_page', 'dashicons-admin-site', 11 );

    add_submenu_page( 'interactive-node-map', 'All Nodes', 'All Nodes', 'manage_options', 'interactive-node-map', 'ikrwmap_ikrwmap_add_admin_menu_page' );
    add_submenu_page( 'interactive-node-map', 'Node 1', 'Node 1', 'manage_options', 'interactive-node-1', 'ikrwmap_node1_page' );

    add_submenu_page( 'interactive-node-map', 'Node 2', 'Node 2', 'manage_options', 'interactive-node-2', 'ikrwmap_node2_page' );
    add_submenu_page( 'interactive-node-map', 'Node 3', 'Node 3', 'manage_options', 'interactive-node-3', 'ikrwmap_node3_page' );
    add_submenu_page( 'interactive-node-map', 'Node 4', 'Node 4', 'manage_options', 'interactive-node-4', 'ikrwmap_node4_page' );
    add_submenu_page( 'interactive-node-map', 'Node 5', 'Node 5', 'manage_options', 'interactive-node-5', 'ikrwmap_node5_page' );

    add_submenu_page( 'interactive-node-map', 'Map Shortcode', 'Map Shortcode', 'manage_options', 'interactive-node-map-shortcode', 'ikrwmap_add_show_data', 11 );
}
add_action( 'admin_menu', 'ikrwmap_add_menu_page' );

function ikrwmap_add_show_data() {
    ?>
    <div class="wrap">
        <h1> Map Shortcode</h1>
        <br>
        <h3>Copy the Shortcode and paste it in your page or post</h3>
        <br>
        <h1> <strong>Floor Plan E1 = </strong> [floor_plan_e1]</h1>
        <h1> <strong>Floor plan E2 = </strong> [floor_plan_e2]</h1>
    </div>
    <?php
}

/* ---------- Activation: create DB (if function exists) ---------- */
if ( function_exists( 'register_activation_hook' ) ) {
    register_activation_hook( __FILE__, 'ikrwmap_plugin_create_tables' ); // original db activation if present
}

/* ===================================================================
   Plugin templates + auto-create pages on activation
   =================================================================== */

/**
 * Template keys and human names
 */
if ( ! defined( 'IKRWMAP_PRICE_TEMPLATE_KEY' ) ) {
    define( 'IKRWMAP_PRICE_TEMPLATE_KEY', 'price-list-plugin-template.php' );
}
if ( ! defined( 'IKRWMAP_PRICE_TEMPLATE_NAME' ) ) {
    define( 'IKRWMAP_PRICE_TEMPLATE_NAME', 'Price List (Interactive Node Map)' );
}

if ( ! defined( 'IKRWMAP_SINGLE_NODE_TEMPLATE_KEY' ) ) {
    define( 'IKRWMAP_SINGLE_NODE_TEMPLATE_KEY', 'single-node-plugin-template.php' );
}
if ( ! defined( 'IKRWMAP_SINGLE_NODE_TEMPLATE_NAME' ) ) {
    define( 'IKRWMAP_SINGLE_NODE_TEMPLATE_NAME', 'Single Node (Interactive Node Map)' );
}

/**
 * Clear the WP page-template transient so WP picks up new templates.
 */
function ikrwmap_clear_page_templates_cache() {
    $theme_root  = get_theme_root();
    $stylesheet  = get_stylesheet();
    $cache_key   = 'page_templates-' . md5( $theme_root . '/' . $stylesheet );
    delete_transient( $cache_key );
}

/**
 * Ensure templates directory exists and write plugin template files if missing.
 * Returns array of template paths on success or false on failure.
 */
function ikrwmap_create_template_files_if_missing() {
    $templates_dir = IKRWMAP_ROBIN_DIR_PATH_WORLD . 'templates/';
    if ( ! file_exists( $templates_dir ) ) {
        @mkdir( $templates_dir, 0755, true );
    }

    $created = array();

    // PRICE LIST TEMPLATE
    $price_path = $templates_dir . IKRWMAP_PRICE_TEMPLATE_KEY;
    if ( ! file_exists( $price_path ) ) {
        $price_content = <<<'PHP'
<?php
/**
 * Plugin template file: Price List
 * Filename: price-list-plugin-template.php
 *
 * This template is generated by Interactive Node Map plugin.
 * Replace it in the plugin's templates/ folder or copy to your theme to customize.
 */

defined('ABSPATH') || exit;

get_header();
?>
<div id="ikrwmap-price-list" class="ikrwmap-plugin-wrap" style="padding:24px;">
  <div class="wrap">
    <h1>Price List (plugin template)</h1>
    <p>Use this page to display your interactive price list or map summary. Replace this template in <code>plugins/interactive-node-map/templates/<?php echo IKRWMAP_PRICE_TEMPLATE_KEY; ?></code> with your desired HTML/CSS/JS or include plugin partials.</p>

    <div id="ikrwmap-content">
      <!-- Example area: you can include your map shortcodes or node-summary partials here -->
      <p>This area is a placeholder. You can render the map shortcode, example: <code>[all-nodes-map]</code></p>
      <?php
        // Example: render shortcode if you want the map here
        if ( shortcodes_exist() ) {
            echo do_shortcode('[all-nodes-map]');
        } else {
            // If your plugin provides a function to echo map, call it here.
            // echo ikrnode_map_all_nodes();
        }
      ?>
    </div>
  </div>
</div>
<?php
get_footer();
PHP;
        @file_put_contents( $price_path, $price_content );
    }
    if ( file_exists( $price_path ) ) {
        $created['price'] = $price_path;
    }

    // SINGLE NODE TEMPLATE
    $single_path = $templates_dir . IKRWMAP_SINGLE_NODE_TEMPLATE_KEY;
    if ( ! file_exists( $single_path ) ) {
        $single_content = <<<'PHP'
<?php
/**
 * Plugin template file: Single Node
 * Filename: single-node-plugin-template.php
 *
 * This template shows a unique style for a single node.
 * Example usage: /node-details?node=123
 */

defined('ABSPATH') || exit;

get_header();
?>
<div id="ikrwmap-single-node" class="ikrwmap-plugin-wrap" style="padding:24px;">
  <div class="wrap">
    <h1>Node Details</h1>
    <p>This page is intended to display a single node in a dedicated layout. The node id can be passed via query string, for example: <code>/node-details?node=123</code>.</p>

    <div id="ikrwmap-node-container" aria-live="polite">
      <div id="ikrwmap-node-loading">Loading node details…</div>
      <div id="ikrwmap-node-content" style="display:none;">
        <!-- JS will fill this area with node details fetched from REST or preloaded JSON -->
      </div>
    </div>

    <script>
    (function(){
      // Basic client-side logic to load node JSON via REST on page load
      function qs(key) {
        var params = new URLSearchParams(window.location.search);
        return params.get(key);
      }
      var nodeId = qs('node');
      var container = document.getElementById('ikrwmap-node-content');
      var loading = document.getElementById('ikrwmap-node-loading');

      if (!nodeId) {
        loading.textContent = 'No node specified. Please open this page with ?node=ID';
        return;
      }

      // fetch via WP REST API endpoint (protocol-relative)
      var restUrl = (window.location.origin || '') + '/wp-json/ikrmap/v1/node/' + encodeURIComponent(nodeId);

      fetch(restUrl, { credentials: 'same-origin' })
        .then(function(res){ if(!res.ok) throw new Error('Network'); return res.json(); })
        .then(function(data){
          loading.style.display = 'none';
          container.style.display = 'block';
          container.innerHTML = '<h2>' + (data.title || 'Untitled') + '</h2>' +
                                '<p><strong>Size:</strong> ' + (data.ikr_size || '-') + '</p>' +
                                '<p><strong>Build sponsor:</strong> ' + (data.room_build_sponsore || '-') + '</p>' +
                                '<p><strong>Description:</strong> ' + (data.map_des || '-') + '</p>';
          // Add your custom single-node styles or map visualization here
        })
        .catch(function(err){
          loading.textContent = 'Failed to load node: ' + err.message;
        });
    })();
    </script>

  </div>
</div>
<?php
get_footer();
PHP;
        @file_put_contents( $single_path, $single_content );
    }
    if ( file_exists( $single_path ) ) {
        $created['single'] = $single_path;
    }

    return $created;
}

/**
 * Create (or ensure) a page exists and assign our plugin template.
 * Returns the page ID on success, false on failure.
 */
function ikrwmap_create_plugin_page( $slug, $title, $template_key ) {
    // Attempt to find existing page by path
    $existing = get_page_by_path( $slug );
    if ( $existing ) {
        // assign template if not assigned
        update_post_meta( $existing->ID, '_wp_page_template', $template_key );
        return $existing->ID;
    }

    $current_user_id = get_current_user_id() ?: 1; // fallback to 1 if unknown
    $page_data = array(
        'post_title'   => $title,
        'post_name'    => $slug,
        'post_content' => 'This page is created by the Interactive Node Map plugin and uses a plugin template.',
        'post_status'  => 'publish',
        'post_type'    => 'page',
        'post_author'  => $current_user_id,
    );

    $page_id = wp_insert_post( $page_data );
    if ( is_wp_error( $page_id ) || ! $page_id ) {
        return false;
    }

    update_post_meta( $page_id, '_wp_page_template', $template_key );
    return $page_id;
}

/**
 * Activation callback: ensure template files exist and pages created/assigned.
 */
function ikrwmap_on_plugin_activation() {
    // create templates (if possible)
    $created = ikrwmap_create_template_files_if_missing();

    // clear cache so WP picks up templates
    ikrwmap_clear_page_templates_cache();

    // create pages and assign templates
    ikrwmap_create_plugin_page( 'price-list', 'Price List', IKRWMAP_PRICE_TEMPLATE_KEY );
    ikrwmap_create_plugin_page( 'node-maps', 'Node Maps', IKRWMAP_SINGLE_NODE_TEMPLATE_KEY );

    // call existing DB creation if present (the original plugin also registered it)
    if ( function_exists( 'ikrwmap_plugin_create_tables' ) ) {
        // call without error if it already ran
        ikrwmap_plugin_create_tables();
    }
}
if ( function_exists( 'register_activation_hook' ) ) {
    register_activation_hook( __FILE__, 'ikrwmap_on_plugin_activation' );
}

/**
 * Admin-init fallback: if plugin was added after activation or activation didn't run,
 * ensure template files and page exist for admins.
 */
add_action( 'admin_init', function() {
    if ( ! current_user_can( 'manage_options' ) ) {
        return;
    }

    ikrwmap_create_template_files_if_missing();
    ikrwmap_clear_page_templates_cache();

    if ( ! get_page_by_path( 'price-list' ) ) {
        ikrwmap_create_plugin_page( 'price-list', 'Price List', IKRWMAP_PRICE_TEMPLATE_KEY );
    }
    if ( ! get_page_by_path( 'node-details' ) ) {
        ikrwmap_create_plugin_page( 'node-details', 'Node Details', IKRWMAP_SINGLE_NODE_TEMPLATE_KEY );
    }
} );

/**
 * Register plugin templates so they show up in the page template dropdown.
 */
add_filter( 'theme_page_templates', function( $post_templates ) {
    $post_templates[ IKRWMAP_PRICE_TEMPLATE_KEY ] = IKRWMAP_PRICE_TEMPLATE_NAME;
    $post_templates[ IKRWMAP_SINGLE_NODE_TEMPLATE_KEY ] = IKRWMAP_SINGLE_NODE_TEMPLATE_NAME;
    return $post_templates;
} );

/**
 * When WordPress resolves the template for a page, return plugin template file if selected.
 */
add_filter( 'page_template', function( $page_template ) {
    if ( is_admin() ) {
        return $page_template;
    }

    global $post;
    if ( ! $post ) {
        return $page_template;
    }

    $selected = get_post_meta( $post->ID, '_wp_page_template', true );
    if ( $selected === IKRWMAP_PRICE_TEMPLATE_KEY ) {
        $plugin_template = IKRWMAP_ROBIN_DIR_PATH_WORLD . 'templates/' . IKRWMAP_PRICE_TEMPLATE_KEY;
        if ( file_exists( $plugin_template ) ) {
            return $plugin_template;
        } else {
            error_log( 'Interactive Node Map: plugin price template not found at ' . $plugin_template );
        }
    }

    if ( $selected === IKRWMAP_SINGLE_NODE_TEMPLATE_KEY ) {
        $plugin_template = IKRWMAP_ROBIN_DIR_PATH_WORLD . 'templates/' . IKRWMAP_SINGLE_NODE_TEMPLATE_KEY;
        if ( file_exists( $plugin_template ) ) {
            return $plugin_template;
        } else {
            error_log( 'Interactive Node Map: plugin single-node template not found at ' . $plugin_template );
        }
    }

    return $page_template;
} );

/**
 * Fallback for block themes: force-include plugin template when visiting plugin pages.
 * This ensures the page will show plugin template even when block theme editor doesn't surface classic templates.
 */
add_action( 'template_redirect', function() {
    if ( is_admin() ) {
        return;
    }

    // Force include for price-list
    if ( function_exists( 'is_page' ) && is_page( 'price-list' ) ) {
        $plugin_template = IKRWMAP_ROBIN_DIR_PATH_WORLD . 'templates/' . IKRWMAP_PRICE_TEMPLATE_KEY;
        if ( file_exists( $plugin_template ) ) {
            include $plugin_template;
            exit;
        }
    }

    // Force include for node-details
    if ( function_exists( 'is_page' ) && is_page( 'node-details' ) ) {
        $plugin_template = IKRWMAP_ROBIN_DIR_PATH_WORLD . 'templates/' . IKRWMAP_SINGLE_NODE_TEMPLATE_KEY;
        if ( file_exists( $plugin_template ) ) {
            include $plugin_template;
            exit;
        }
    }

}, 1 );

